### ISSUE TITLE
Improve unit tests for DataDog reporter

### ISSUE THREAD

**Issue by nivancevic** [smartcat-labs/cassandra-diagnostics#221]
Test UDP server causes BindException (Address already in use) in unit tests for datadog reporter.
Test UDP server could be started @BeforeClass and stopped @AfterClass. Also, it could be moved to integration tests.

**Comment by nbozic-zz** [comment]
Address already in use is just a symptom, not real problem (one test method fails, UDP server stays hanging and next test has bind address problem.

Still this is scary test, and it is testing more than it should do since we need to test client and not the server receiving messages. Test should be reworked to mock client sending messages and verify number of times message is sent.

**Comment by nbozic-zz** [comment]
Fixed issue with occasional failing of this test and documented improvement idea in #241
